### PR TITLE
regex support on find_elements closes #21

### LINKED ISSUE #21: Regex support on find_elements
`find_elements` function works only in full match case.

```Python
>>> list_to_be_splited = ['spam', 1, 2, 3, 'eggs', 1, 2, 3, 'foo', 1, 2, 3]
>>> split_by = ['spam', 'eggs', 'foo']

>>> splited = find_elements(list_to_be_splited, split_by)
# [(0, 'spam'), (4, 'eggs'), (8, 'foo')]
```
And `list_by_re_pattern` matches one regex.

In my opinion using splitty yesterday with @rg3915, we saw a dependency. Something like that:

```
root      1978  0.2  0.8 1534468 69680 ?       Ssl  09:12   0:01 /usr/bin/dockerd -H fd://
root      2141  0.1  0.4 1244864 34892 ?       Ssl  09:12   0:01 docker-containerd --config /var/run/docker/containerd/containerd.toml
root      2706  0.0  0.0 379496  3832 ?        Sl   09:12   0:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 5432 -container-ip 192.202.112.2
...
eduardo+  6136  0.0  0.0  14440  1108 pts/0    S+   09:24   0:00 grep --color=auto docker
```

If i need catch all docker process intervals, or we list all docker commands or create a biggest regex.

in that case it would be simpler a basix expression in list_by_list:

```Python
>>> list_to_be_splited = '''
root      1978  0.2  0.8 1534468 69680 ?       Ssl  09:12   0:01 /usr/bin/dockerd -H fd://
root      2141  0.1  0.4 1244864 34892 ?       Ssl  09:12   0:01 docker-containerd --config /var/run/docker/containerd/containerd.toml
root      2706  0.0  0.0 379496  3832 ?        Sl   09:12   0:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 5432 -container-ip 192.202.112.2
...
eduardo+  6136  0.0  0.0  14440  1108 pts/0    S+   09:24   0:00 grep --color=auto docker
'''

>>> split_by = [r'/usr/bin/docker-\w+, r' /var/run/docker/.+\.toml', 'foo', 'bar']
```

### PR DESCRIPTION
**Pull request by dunossauro**
Closes #21

### CODE REVIEW

**Comment by dunossauro** [comment]
Anyone can review this code?

@williangl, @rg3915 ... ???

**Comment by rg3915** [comment]
> Anyone can review this code?
> 
> @williangl, @rg3915 ... ???
:+1:

**Comment by dunossauro** [comment]
@meiralins posso mergear? xD

**Comment by meiralins** [comment]
@dunossauro I took another look and it's missing tests of the default behavior of the ```_num_or_match```.
Perhaps you could implement the ```Number``` behavior in the default behavior. In this way, it would be tested and you add support for other types.

Also, consider renaming ```_num_or_match```. Perharps ```matcher``` would do.

**Pull request merged**
